### ISSUE TITLE
LocalNotifications on IOS don't work

### ISSUE THREAD

**Issue by KonstantinNemo** [bluecats/bluecats-phonegap#1] opened 2015-05-05 06:57 UTC
On Android local notifications work just fine, although on IOS none of the scheduled notifications show up when coming close to the related beacon.

**Comment by damoclarke** [comment] 2015-05-06 05:46
I have checked into local notifications using the phone gap plugin and the issue is that a permission request required for iOS 8.0 is not automatically included by the plugin.

This is the explanation from the Native SDK documentation:
https://github.com/bluecats/bluecats-ios-sdk/wiki/Local-Notifications#ios-80-local-notification-permission

We will need include options to request permissions via the plugin, but in the meantime as a work-around in the you can include the following code in your iOS application's AppDelegate -

    (BOOL)application:(UIApplication*)application didFinishLaunchingWithOptions:(NSDictionary*)launchOptions

The following code can be placed at the end of the method, before the return statement:

    if ([[UIApplication sharedApplication]      respondsToSelector:@selector(registerUserNotificationSettings:)]) {
        [[UIApplication sharedApplication] registerUserNotificationSettings:[UIUserNotificationSettings settingsForTypes:(UIUserNotificationTypeSound | UIUserNotificationTypeAlert | UIUserNotificationTypeBadge) categories:nil]];
    }

return YES;

This causes a dialogue to be displayed requesting permission to display notifications. Prior to iOS 8 this permission request was not required for local notifications. We are investigating including this step automatically with the plugin, but in the meantime please let me know if you are able to add manually and receive notifications.

**Comment by KonstantinNemo** [comment] 2015-05-06 07:07
Thx for your quick reply with the solution, i'd highly appreciate it if this becomes part of the plugin. :-) 

Were using the feature and create platforms on the fly at build-time so we cant directly modify them.

**Closed** 2016-02-19 03:47 UTC
